# fastapi_app.py
"""
NOVA backend — local-first with optional cloud LLM.

Architecture (replaces the TensorFlow encoder stack):
  - Chat brain      : Llama-3.2-3B-Instruct — local via Ollama (Unsloth GGUF)
                      or Groq API in cloud deploys (same weights)
  - Text emotions   : j-hartmann/emotion-english-distilroberta-base (HF)
  - Face emotions   : trpakov/vit-face-expression (HF, FER2013)
  - Voice emotions  : superb/wav2vec2-base-superb-er (HF)
  - Safety          : keyword crisis layer (unchanged)
  - Reports         : generated by the LLM (was: Google Gemini)

Provider selection: LLM_PROVIDER env var (auto | ollama | groq).
The client stays local-first: chat runs here; Gemini is only used as a
client-side fallback if this server is unreachable.
"""

import sys
import os
import logging
import base64
import tempfile
from contextlib import asynccontextmanager
from typing import Optional, List, Dict

import numpy as np
import cv2
from PIL import Image
from io import BytesIO

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from emotional_ai_llm.config import EMOTION_LABELS
from emotional_ai_llm.emotion_detectors import get_detector
from emotional_ai_llm.response_planner import ResponsePlanner
from emotional_ai_llm.report_generator import generate_analysis_report
from emotional_ai_llm.safety_layer import SafetyLayer
from emotional_ai_llm.output_actions import OutputActions
from emotional_ai_llm.reporter import Reporter
from emotional_ai_llm.llm_engine import get_llm_engine

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Global components (initialized in lifespan) ---
detector = None
planner = None
safety_checker = None
output_handler = None
reporter = None
llm_engine = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize all AI components on startup (models load lazily on first use)."""
    global detector, planner, safety_checker, output_handler, reporter, llm_engine

    logging.info("Initializing NOVA components...")
    llm_engine = get_llm_engine()
    if llm_engine.is_available(force_check=True):
        logging.info(f"LLM provider: {llm_engine.provider} — chat brain: {llm_engine.model}")
    else:
        logging.warning(
            "No LLM provider available! Chat will use fallback responses. "
            "Start Ollama locally or set GROQ_API_KEY."
        )

    detector = get_detector()          # HF emotion models
    planner = ResponsePlanner(EMOTION_LABELS)
    safety_checker = SafetyLayer()
    output_handler = OutputActions()
    reporter = Reporter()

    # Warm up emotion models at boot so the first user request is fast
    # (on Render this also triggers the one-time HF download during startup)
    logging.info("Warming up emotion models...")
    detector.warm_up()

    logging.info("NOVA components initialized. Ready.")

    yield
    logging.info("Shutting down NOVA backend.")


app = FastAPI(title="NOVA Emotional AI Backend", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Request / Response models ---


class HistoryMessage(BaseModel):
    role: str  # "user" | "assistant"
    content: str


class ChatRequest(BaseModel):
    text: str
    emotion: str = "neutral"
    image: Optional[str] = None   # base64 encoded image
    audio: Optional[str] = None   # base64 encoded audio
    history: Optional[List[HistoryMessage]] = None


class AnalysisData(BaseModel):
    moodScore: float
    emotionalBreakdown: List[dict]
    userFacialEmotion: str
    overallSummary: dict
    insights: List[dict]


class ChatResponse(BaseModel):
    response: str
    safe: bool
    dominant_emotions: str
    confidence: float
    reasoning: str
    suggested_actions: List[str]
    analysisData: AnalysisData


class ReportRequest(BaseModel):
    history: List[HistoryMessage]


# --- Helpers ---


def _decode_image(image_base64: str) -> Optional[np.ndarray]:
    """Decode a base64 image (with or without data-URL prefix) to an RGB array."""
    try:
        if "base64," in image_base64:
            _, image_base64 = image_base64.split("base64,", 1)
        image_bytes = base64.b64decode(image_base64)
        image_array = np.array(Image.open(BytesIO(image_bytes)))
        if image_array.ndim == 3 and image_array.shape[2] == 4:
            image_array = cv2.cvtColor(image_array, cv2.COLOR_RGBA2RGB)
        elif image_array.ndim == 2:
            image_array = cv2.cvtColor(image_array, cv2.COLOR_GRAY2RGB)
        return image_array
    except Exception as e:
        logging.error(f"Error decoding image: {e}")
        return None


def _decode_audio_to_tempfile(audio_base64: str) -> Optional[str]:
    """Decode base64 audio to a temp wav file. Returns path or None."""
    try:
        if "base64," in audio_base64:
            _, audio_base64 = audio_base64.split("base64,", 1)
        audio_bytes = base64.b64decode(audio_base64)
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmp:
            tmp.write(audio_bytes)
            return tmp.name
    except Exception as e:
        logging.error(f"Error decoding audio: {e}")
        return None


def _mood_score(emotion_probabilities) -> float:
    """Map the fused emotion distribution to a 0-10 mood score."""
    mood_weights = {
        "happy": 1.0, "surprise": 0.6, "neutral": 0.5,
        "fear": 0.25, "sad": 0.2, "disgust": 0.2, "anger": 0.15,
    }
    score = sum(prob * mood_weights.get(label, 0.5)
                for label, prob in zip(EMOTION_LABELS, emotion_probabilities))
    return round(score * 10, 1)


def _crisis_response(user_facial_emotion: str) -> ChatResponse:
    response_text = (
        "I'm really glad you told me. You don't have to carry this alone — "
        "please reach out to a crisis helpline (988 in the US) or someone you "
        "trust right now. I'm connecting you to a human expert."
    )
    return ChatResponse(
        response=response_text,
        safe=False,
        dominant_emotions="crisis",
        confidence=1.0,
        reasoning="Crisis language detected in user input.",
        suggested_actions=["Human escalation triggered", "Contact a crisis helpline"],
        analysisData=AnalysisData(
            moodScore=0,
            emotionalBreakdown=[],
            userFacialEmotion=user_facial_emotion,
            overallSummary={"status": "Crisis", "trend": "N/A", "recommendation": response_text},
            insights=[{"title": "Safety Alert", "description": "Crisis language detected."}],
        ),
    )


# --- Endpoints ---


@app.post("/chat", response_model=ChatResponse)
async def chat(request_data: ChatRequest):
    user_input_text = (request_data.text or "").strip()
    user_facial_emotion = request_data.emotion or "neutral"
    history = [h.dict() for h in request_data.history] if request_data.history else None

    if not user_input_text and not request_data.image and not request_data.audio:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="No text, image or audio input provided")

    # If only media was sent, use a light prompt for the LLM
    if not user_input_text:
        user_input_text = (
            "(The user shared a facial expression for you to react to.)"
            if request_data.image else
            "(The user sent a voice message for you to react to.)"
        )

    logging.info(f"Chat request: '{user_input_text[:80]}' facial_emotion='{user_facial_emotion}'")

    interaction_data = {
        "user_input": user_input_text,
        "user_facial_emotion": user_facial_emotion,
        "ai_response": "",
        "dominant_emotions": "",
        "suggested_actions": [],
        "safety_flag_user_input": False,
        "safety_flag_ai_response": False,
        "crisis_keywords_user": [],
        "crisis_keywords_ai": [],
    }

    # 1. Safety check on user input
    is_crisis_input, crisis_keywords = safety_checker.check_for_crisis_language(user_input_text)
    if is_crisis_input:
        logging.warning("Crisis language detected in user input.")
        output_handler.escalate_to_human(reason="Crisis language in user input",
                                         text_to_escalate=user_input_text)
        interaction_data.update({
            "ai_response": "Crisis escalation response sent.",
            "safety_flag_user_input": True,
            "crisis_keywords_user": crisis_keywords,
        })
        reporter.log_interaction(interaction_data)
        return _crisis_response(user_facial_emotion)

    # 2. Multimodal emotion analysis (pretrained HF models)
    text_probs = detector.analyze_text(user_input_text) if user_input_text else None

    face_probs = None
    if request_data.image:
        image_array = _decode_image(request_data.image)
        if image_array is not None:
            face_probs = detector.analyze_face(image_array)
            top_face = max(face_probs, key=face_probs.get)
            if face_probs[top_face] > 0.35:
                user_facial_emotion = top_face

    voice_probs = None
    audio_temp_path = None
    if request_data.audio:
        audio_temp_path = _decode_audio_to_tempfile(request_data.audio)
        if audio_temp_path:
            try:
                voice_probs = detector.analyze_voice(audio_temp_path)
            finally:
                try:
                    os.remove(audio_temp_path)
                except OSError:
                    pass

    fused = detector.fuse(text_probs=text_probs, face_probs=face_probs,
                          voice_probs=voice_probs, client_emotion=user_facial_emotion)
    emotion_probabilities = np.array([fused[label] for label in EMOTION_LABELS], dtype=np.float32)
    logging.info(f"Fused emotions: {dict(zip(EMOTION_LABELS, emotion_probabilities.round(3)))}")

    # 3. Generate empathetic response with the local LLM
    empathetic_response_text = planner.generate_empathetic_response(
        user_input_text=user_input_text,
        current_emotion_probabilities=emotion_probabilities,
        user_facial_emotion=user_facial_emotion,
        history=history,
    )

    # 4. Safety check on generated response
    is_crisis_output, crisis_keywords_out = safety_checker.check_for_crisis_language(
        empathetic_response_text)
    if is_crisis_output:
        logging.warning("Crisis language detected in generated response — overriding.")
        output_handler.escalate_to_human(reason="Crisis language in generated response",
                                         text_to_escalate=empathetic_response_text)
        empathetic_response_text = (
            "I want to make sure you get the right support. Let me connect you "
            "with a human expert who can help."
        )
        interaction_data["safety_flag_ai_response"] = True
        interaction_data["crisis_keywords_ai"] = crisis_keywords_out

    # 5. Actions + logging
    dominant_emotions_str = planner._get_dominant_emotions(emotion_probabilities)
    first_emotion = dominant_emotions_str.split(",")[0].strip().lower()
    suggested_actions = output_handler.action_suggestions.get(
        first_emotion, output_handler.action_suggestions["neutral"])

    top_label, top_prob = max(zip(EMOTION_LABELS, emotion_probabilities), key=lambda p: p[1])
    confidence = float(top_prob)
    reasoning = (
        f"Detected '{top_label}' ({confidence:.0%}) from"
        f"{' text' if text_probs else ''}"
        f"{' + facial expression' if face_probs else ''}"
        f"{' + voice tone' if voice_probs else ''}"
        f". Camera reports: {user_facial_emotion}."
    )

    interaction_data.update({
        "ai_response": empathetic_response_text,
        "dominant_emotions": dominant_emotions_str,
        "suggested_actions": suggested_actions,
    })
    reporter.log_interaction(interaction_data)

    # 6. Build client-facing analysis payload
    emotional_breakdown = [
        {
            "emotion": label,
            "value": int(prob * 100),
            "color": "bg-primary" if prob > 0.5 else "bg-accent",
        }
        for label, prob in zip(EMOTION_LABELS, emotion_probabilities)
    ]
    positive = top_label in ("happy", "surprise")
    analysis_data = AnalysisData(
        moodScore=_mood_score(emotion_probabilities),
        emotionalBreakdown=emotional_breakdown,
        userFacialEmotion=user_facial_emotion,
        overallSummary={
            "status": "Positive" if positive else ("Neutral" if top_label == "neutral" else "Negative"),
            "trend": "Stable",
            "recommendation": empathetic_response_text,
        },
        insights=[
            {"title": "Key Emotions", "description": f"Dominant emotions: {dominant_emotions_str}."},
            {"title": "AI Recommendation", "description": empathetic_response_text},
            {"title": "Suggested Next Steps", "description": ", ".join(suggested_actions)},
        ],
    )

    return ChatResponse(
        response=empathetic_response_text,
        safe=not is_crisis_output,
        dominant_emotions=dominant_emotions_str,
        confidence=confidence,
        reasoning=reasoning,
        suggested_actions=suggested_actions,
        analysisData=analysis_data,
    )


@app.post("/report")
async def report(request_data: ReportRequest):
    """Generate a psychological assessment report locally (no Gemini needed)."""
    history = [h.dict() for h in request_data.history]
    logging.info(f"Report request with {len(history)} messages.")
    try:
        report_data = generate_analysis_report(history)
        return report_data
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))
    except Exception as e:
        logging.error(f"Report generation failed: {e}")
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                            detail="Report engine unavailable. Check the LLM provider config.")


@app.get("/health")
async def health():
    """Component status for diagnostics."""
    engine_ok = llm_engine.is_available(force_check=True) if llm_engine else False
    return {
        "status": "ok",
        "llm_provider": llm_engine.provider if llm_engine else None,
        "llm_model": llm_engine.model if llm_engine else None,
        "llm_available": engine_ok,
        "emotion_modalities": {
            "text": detector is not None,
        },
    }


@app.get("/reports")
async def get_reports():
    logs = reporter.get_all_logs()
    logging.info(f"Retrieved {len(logs)} interaction logs.")
    return logs


@app.get("/")
async def read_root():
    return {"message": "NOVA Emotional AI Backend is running.", "docs": "/docs"}
