# emotional_ai_llm/response_planner.py

import numpy as np
import random
import logging # Added logging
from langchain_core.prompts import PromptTemplate

class ResponsePlanner:
    def __init__(self, emotion_labels, detection_threshold=0.5): # Added detection_threshold
        """
        Initializes the ResponsePlanner with known emotion labels and a detection threshold.

        Args:
            emotion_labels (list): A list of strings representing the emotion labels
                                   the fusion module outputs.
            detection_threshold (float): Probability threshold above which an emotion is considered dominant.
        """
        self.emotion_labels = emotion_labels
        self.detection_threshold = detection_threshold # Store threshold
        self.prompt_template = PromptTemplate(
            input_variables=["dominant_emotions", "conversation_context"],
            template="""You are an empathetic AI assistant.
Based on the current emotional state of the user and the conversation history, generate a supportive and empathetic response.

Current dominant emotions: {dominant_emotions}
Conversation history summary: {conversation_context}

Your empathetic response:"""
        )
        logging.info(f"ResponsePlanner initialized with {len(emotion_labels)} emotion labels and threshold {detection_threshold}.")

    def _get_dominant_emotions(self, emotion_probabilities):
        """
        Identifies dominant emotions based on probabilities and the configured threshold.
        Logs raw probabilities for debugging.
        """
        logging.debug(f"Raw emotion probabilities: {emotion_probabilities}")
        logging.debug(f"Emotion labels: {self.emotion_labels}")

        dominant_emotions = []
        for i, prob in enumerate(emotion_probabilities):
            if prob > self.detection_threshold: # Use instance threshold
                dominant_emotions.append(self.emotion_labels[i])
        
        if not dominant_emotions: # If no emotion passes threshold, pick the highest one
            max_prob_idx = np.argmax(emotion_probabilities)
            dominant_emotions.append(self.emotion_labels[max_prob_idx])
            logging.debug(f"No emotions above threshold {self.detection_threshold}, selected highest: {self.emotion_labels[max_prob_idx]}")
        
        return ", ".join(dominant_emotions) if dominant_emotions else "neutral"

    def generate_empathetic_response(self, current_emotion_probabilities, conversation_context_vector):
        """
        Generates an empathetic response based on current emotions and conversation context.
        For now, this simulates an LLM response.

        Args:
            current_emotion_probabilities (np.array): Probabilities for each emotion from the fusion module.
            conversation_context_vector (np.array): Recency-weighted context vector from the memory module.

        Returns:
            str: An empathetic response.
        """
        dominant_emotions_str = self._get_dominant_emotions(current_emotion_probabilities)
        
        # Simulate conversation context summary from the context vector
        # In a real scenario, this would be generated by a separate component
        # that interprets the context vector into a human-readable summary.
        simulated_context_summary = f"User has expressed {dominant_emotions_str} emotions. Past interactions indicate a generally {'positive' if np.mean(conversation_context_vector) > 0.5 else 'negative'} tone."

        # Format the prompt using LangChain's PromptTemplate
        formatted_prompt = self.prompt_template.format(
            dominant_emotions=dominant_emotions_str,
            conversation_context=simulated_context_summary
        )

        print(f"""
--- Simulated LLM Prompt --- 
{formatted_prompt}
--- End Simulated Prompt ---
""")

        # --- Simulate LLM response ---
        # In a real scenario, you would call an LLM endpoint here:
        # llm = SomeLLM(...)
        # response = llm(formatted_prompt)
        
        # Simple rule-based simulation for now
        if "happy" in dominant_emotions_str or "joy" in dominant_emotions_str:
            response = random.choice([
                "That's wonderful to hear! I'm glad you're feeling positive.",
                "It sounds like things are going well. Keep up the good spirits!",
                "Your positive energy is contagious!"
            ])
        elif "sad" in dominant_emotions_str or "grief" in dominant_emotions_str:
            response = random.choice([
                "I'm sorry to hear that you're feeling down. I'm here for you.",
                "It's okay to feel sad sometimes. Take your time.",
                "Remember that even in difficult times, there's hope for better days."
            ])
        elif "angry" in dominant_emotions_str or "annoyance" in dominant_emotions_str:
            response = random.choice([
                "I understand you're feeling angry. It's important to acknowledge that.",
                "It sounds like you're going through something frustrating. How can I help?",
                "Take a deep breath. Let's try to work through this together."
            ])
        elif "surprise" in dominant_emotions_str or "excitement" in dominant_emotions_str:
            response = random.choice([
                "Oh, that's surprising! Tell me more about it.",
                "Wow, what an exciting development!",
                "I'm intrigued by what you're experiencing!"
            ])
        else: # Default or neutral response
            response = random.choice([
                "I'm listening. Please tell me more.",
                "How are you feeling about that?",
                "I'm here to support you in any way I can."
            ])
        
        return response

if __name__ == "__main__":
    print("Running ResponsePlanner module development example:")

    # Example emotion labels (must match NUM_EMOTION_LABELS from fusion_module.py)
    EMOTION_LABELS = ['anger', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral']
    NUM_EMOTION_LABELS = len(EMOTION_LABELS)
    EMBEDDING_DIM = 384 # From fusion module

    planner = ResponsePlanner(EMOTION_LABELS)

    # Simulate current emotion probabilities (e.g., from fusion module output)
    current_emotions_happy = np.array([0.1, 0.05, 0.05, 0.8, 0.1, 0.05, 0.1]) # Dominant: happy
    current_emotions_sad_angry = np.array([0.7, 0.1, 0.1, 0.05, 0.6, 0.05, 0.1]) # Dominant: angry, sad
    current_emotions_neutral = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]) # Dominant: neutral

    # Simulate conversation context vector (e.g., from memory module output)
    conversation_context_pos = np.random.rand(EMBEDDING_DIM) # Simulate positive context
    conversation_context_neg = np.random.rand(EMBEDDING_DIM) - 0.5 # Simulate negative context

    # Test cases
    print("\n--- Test Case 1: Happy Emotion ---")
    response1 = planner.generate_empathetic_response(current_emotions_happy, conversation_context_pos)
    print(f"Generated Response: {response1}")

    print("\n--- Test Case 2: Sad and Angry Emotions ---")
    response2 = planner.generate_empathetic_response(current_emotions_sad_angry, conversation_context_neg)
    print(f"Generated Response: {response2}")

    print("\n--- Test Case 3: Neutral Emotion ---")
    response3 = planner.generate_empathetic_response(current_emotions_neutral, conversation_context_pos)
    print(f"Generated Response: {response3}")

    print("\nResponsePlanner module development example finished.")
